### ISSUE TITLE
fs.rename() can't move file between two different disks

### ISSUE THREAD

**Issue by wenbing** [cnpm/sfs#4]
https://github.com/joyent/node/issues/2703

**Comment by dead-horse** [comment]
only need to support `*nix`

**Comment by wenbing** [comment]
@dead-horse *nix 同样存在这个问题
http://stackoverflow.com/questions/4568689/how-do-i-move-file-a-to-a-different-partition-or-device-in-node-js

**Comment by dead-horse** [comment]
可以配置到同一个 disk 下吧，没必要为了这个改代码

**Comment by wenbing** [comment]
`connect-multiparty` 可以传入 uploadDir , 不过 routes/web.js 中没有传入，所以使用了系统的 os.tmpDir() 
需要修改代码，做到可配置 uploadDir
或者
解决这个问题

**Comment by fengmk2** [comment]
@wenbing 可以自定义上传临时文件夹了

**Comment by rambo-panda** [comment]
可以尝试自己写一个文件

``` javascript
var ins = fs.createReadStream(source);
var outs = fs.createWriteStream(dest);
```
